#!/usr/bin/env python3

import os
import signal
import subprocess
import sys
import time
from pathlib import Path


# ============================================================
# BASIS
# PHASE 2 - FIVE DRONE GAZEBO SWARM LAUNCHER
#
# PX4 + Gazebo Sim + ROS 2
#
# 5 x X500
#
# PX4 instances:
#     1, 2, 3, 4, 5
#
# ROS namespaces:
#     /px4_1
#     /px4_2
#     /px4_3
#     /px4_4
#     /px4_5
#
# ============================================================


# ------------------------------------------------------------
# PATHS
# ------------------------------------------------------------

PX4_DIR = Path.home() / "PX4-Autopilot"

PX4_BINARY = (
    PX4_DIR
    / "build"
    / "px4_sitl_default"
    / "bin"
    / "px4"
)

# PX4 POSIX startup directory.
PX4_INIT_DIR = (
    PX4_DIR
    / "ROMFS"
    / "px4fmu_common"
    / "init.d-posix"
)

# BASIS custom configuration.
BASIS_CONFIG_DIR = (
    PX4_DIR
    / "build"
    / "basis_sitl_config"
)

BASIS_CONFIG_FILE = BASIS_CONFIG_DIR / "config.txt"


# ------------------------------------------------------------
# SWARM CONFIGURATION
# ------------------------------------------------------------

NUM_DRONES = 5

SPAWN_POSITIONS = [
    (0.0, 0.0, 0.0),       # Drone 1
    (5.0, 0.0, 0.0),       # Drone 2
    (-5.0, 0.0, 0.0),      # Drone 3
    (0.0, 5.0, 0.0),       # Drone 4
    (0.0, -5.0, 0.0),      # Drone 5
]


# ------------------------------------------------------------
# GLOBAL PROCESS LIST
# ------------------------------------------------------------

processes = []


# ============================================================
# BASIS PX4 CONFIGURATION
# ============================================================

def create_basis_config():
    """
    Create a PX4 POSIX config.txt containing the parameters
    required by the BASIS ROS2-only SITL swarm.

    PX4 loads this after its normal startup configuration.
    Therefore these values are actual PX4 parameters rather
    than ordinary Linux environment variables.
    """

    BASIS_CONFIG_DIR.mkdir(parents=True, exist_ok=True)

    config = """# ============================================================
# BASIS SITL CONFIGURATION
#
# Automatically generated by swarm_launcher.py
# ============================================================

# ------------------------------------------------------------
# ROS2 / OFFBOARD SITL
# ------------------------------------------------------------

# Do not require Remote ID for arming.
param set COM_ARM_ODID 0

# Do not trigger an RC-loss action.
param set NAV_RCL_ACT 0

# Do not trigger a data-link-loss action.
param set NAV_DLL_ACT 0

# PX4 SITL does not require an RC calibration/configuration.
param set COM_RC_IN_MODE 1

# ------------------------------------------------------------
# SITL RESOURCE CHECKS
# ------------------------------------------------------------

# POSIX SITL does not report CPU/RAM load like hardware.
param set COM_CPU_MAX -1
param set COM_RAM_MAX -1

# ------------------------------------------------------------
# END BASIS CONFIGURATION
# ------------------------------------------------------------
"""

    BASIS_CONFIG_FILE.write_text(config)

    print()
    print("----------------------------------------------")
    print("BASIS PX4 CONFIGURATION")
    print("----------------------------------------------")
    print(f"Config file: {BASIS_CONFIG_FILE}")
    print()
    print("Parameters:")
    print("  COM_ARM_ODID = 0")
    print("  NAV_RCL_ACT  = 0")
    print("  NAV_DLL_ACT  = 0")
    print("  COM_RC_IN_MODE = 1")
    print()


# ============================================================
# CLEANUP
# ============================================================

def cleanup(signum=None, frame=None):

    print()
    print("==============================================")
    print("Stopping BASIS Phase 2 swarm")
    print("==============================================")

    # Stop PX4 processes gracefully.
    for process in processes:

        if process.poll() is None:

            try:
                process.send_signal(signal.SIGINT)
            except Exception:
                pass

    time.sleep(3)

    # Force kill anything still alive.
    for process in processes:

        if process.poll() is None:

            try:
                process.kill()
            except Exception:
                pass

    print("PX4 processes stopped.")

    sys.exit(0)


# ============================================================
# START PX4 INSTANCE
# ============================================================

def start_px4(instance, x, y, z, standalone):

    env = os.environ.copy()

    # --------------------------------------------------------
    # PX4 AIRFRAME
    # --------------------------------------------------------

    env["PX4_SYS_AUTOSTART"] = "4001"
    env["PX4_SIM_MODEL"] = "gz_x500"

    # --------------------------------------------------------
    # GAZEBO
    # --------------------------------------------------------

    env["PX4_GZ_WORLD"] = "default"
    env["PX4_GZ_MODEL_POSE"] = f"{x},{y},{z}"

    # --------------------------------------------------------
    # ROS 2 / MICRO XRCE-DDS
    # --------------------------------------------------------

    env["PX4_UXRCE_DDS_NS"] = f"px4_{instance}"
    env["PX4_UXRCE_DDS_PORT"] = "8888"

    # --------------------------------------------------------
    # IMPORTANT:
    #
    # These are NOT PX4 parameters.
    #
    # Do NOT put COM_ARM_ODID, NAV_RCL_ACT, or NAV_DLL_ACT
    # into the environment.
    #
    # They are configured through BASIS config.txt.
    # --------------------------------------------------------

    env.pop("COM_ARM_ODID", None)
    env.pop("NAV_RCL_ACT", None)
    env.pop("NAV_DLL_ACT", None)
    env.pop("COM_RC_IN_MODE", None)

    # --------------------------------------------------------
    # GAZEBO STANDALONE
    # --------------------------------------------------------

    if standalone:
        env["PX4_GZ_STANDALONE"] = "1"
    else:
        env.pop("PX4_GZ_STANDALONE", None)

    # --------------------------------------------------------
    # PX4 COMMAND
    # --------------------------------------------------------

    command = [
        str(PX4_BINARY),
        "-i",
        str(instance),
    ]

    print()
    print("----------------------------------------------")
    print(f"STARTING DRONE {instance}")
    print("----------------------------------------------")
    print(f"PX4 instance : {instance}")
    print(f"MAV_SYS_ID   : {instance + 1}")
    print(f"ROS namespace: /px4_{instance}")
    print(f"Spawn        : ({x}, {y}, {z})")
    print(f"Standalone   : {standalone}")
    print()

    process = subprocess.Popen(
        command,
        cwd=str(PX4_DIR),
        env=env,
    )

    processes.append(process)

    return process


# ============================================================
# MAIN
# ============================================================

def main():

    print()
    print("================================================")
    print("      BASIS PHASE 2 - FIVE DRONE SWARM")
    print("================================================")
    print()

    print("PX4       :", PX4_DIR)
    print("PX4 binary:", PX4_BINARY)
    print("World     : default.sdf")
    print("Vehicles  : 5 x X500")
    print()

    # --------------------------------------------------------
    # CHECK PX4
    # --------------------------------------------------------

    if not PX4_BINARY.exists():

        print("ERROR:")
        print("PX4 binary not found:")
        print(PX4_BINARY)
        print()
        print("Build PX4 first:")
        print()
        print("cd ~/PX4-Autopilot")
        print("make px4_sitl")
        print()

        sys.exit(1)

    # --------------------------------------------------------
    # CHECK INIT DIRECTORY
    # --------------------------------------------------------

    if not PX4_INIT_DIR.exists():

        print("ERROR:")
        print("PX4 POSIX init directory not found:")
        print(PX4_INIT_DIR)
        print()

        sys.exit(1)

    # --------------------------------------------------------
    # CREATE BASIS CONFIGURATION
    # --------------------------------------------------------

    create_basis_config()

    # --------------------------------------------------------
    # SIGNAL HANDLERS
    # --------------------------------------------------------

    signal.signal(signal.SIGINT, cleanup)
    signal.signal(signal.SIGTERM, cleanup)

    # --------------------------------------------------------
    # DRONE 1
    #
    # First PX4 instance starts Gazebo.
    # --------------------------------------------------------

    x, y, z = SPAWN_POSITIONS[0]

    start_px4(
        instance=1,
        x=x,
        y=y,
        z=z,
        standalone=False,
    )

    print()
    print("Waiting for Gazebo to initialize...")
    time.sleep(10)

    # --------------------------------------------------------
    # DRONES 2-5
    #
    # Connect to the existing Gazebo instance.
    # --------------------------------------------------------

    for index in range(1, NUM_DRONES):

        instance = index + 1

        x, y, z = SPAWN_POSITIONS[index]

        start_px4(
            instance=instance,
            x=x,
            y=y,
            z=z,
            standalone=True,
        )

        # Give PX4/Gazebo time to initialize.
        time.sleep(5)

    # --------------------------------------------------------
    # WAIT FOR PX4 INITIALIZATION
    # --------------------------------------------------------

    print()
    print("Waiting for all PX4 instances to initialize...")
    print()

    time.sleep(10)

    # --------------------------------------------------------
    # CHECK PROCESSES
    # --------------------------------------------------------

    failed = False

    for index, process in enumerate(processes):

        instance = index + 1

        if process.poll() is not None:

            print(
                f"ERROR: PX4 instance {instance} "
                f"exited during startup."
            )

            failed = True

        else:

            print(
                f"PX4 instance {instance}: RUNNING"
            )

    if failed:

        print()
        print("ERROR: One or more PX4 instances failed.")
        print("Stopping swarm.")

        cleanup()

    # --------------------------------------------------------
    # SUCCESS
    # --------------------------------------------------------

    print()
    print("================================================")
    print("       FIVE DRONES STARTED SUCCESSFULLY")
    print("================================================")
    print()

    print("PX4 instances:")
    print()
    print("    Instance 1 -> MAV_SYS_ID 2 -> /px4_1")
    print("    Instance 2 -> MAV_SYS_ID 3 -> /px4_2")
    print("    Instance 3 -> MAV_SYS_ID 4 -> /px4_3")
    print("    Instance 4 -> MAV_SYS_ID 5 -> /px4_4")
    print("    Instance 5 -> MAV_SYS_ID 6 -> /px4_5")
    print()

    print("PX4 arming configuration:")
    print()
    print("    COM_ARM_ODID = 0")
    print("    NAV_RCL_ACT  = 0")
    print("    NAV_DLL_ACT  = 0")
    print("    COM_RC_IN_MODE = 1")
    print()

    print("ROS 2 namespaces:")
    print()
    print("    /px4_1")
    print("    /px4_2")
    print("    /px4_3")
    print("    /px4_4")
    print("    /px4_5")
    print()

    print("Gazebo world:")
    print("    default.sdf")
    print()

    print("Keep this terminal running.")
    print("Start swarm_controller.py in another terminal.")
    print()

    # --------------------------------------------------------
    # KEEP LAUNCHER ALIVE
    # --------------------------------------------------------

    try:

        while True:

            time.sleep(2)

            for i, process in enumerate(processes):

                if process.poll() is not None:

                    print(
                        f"WARNING: PX4 instance "
                        f"{i + 1} exited."
                    )

    except KeyboardInterrupt:

        cleanup()


# ============================================================
# ENTRY POINT
# ============================================================

if __name__ == "__main__":
    main()

